import type { NextPage } from "next";
import Head from "next/head";
import BootcampCardsList from "../components/BootcampCardsList";
import AddCourseToTheBootcamp from "../components/createCouseHandler/AddCourseToTheBootcamp";
import CreateNewBootcampModal from "../components/createCouseHandler/CreateNewBootcampModal";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import InfoSection from "../components/InfoSection";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main>
        <HeroSection />
        <InfoSection />
        <CreateNewBootcampModal />
        <BootcampCardsList />
      </main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
